watch_stylesheet: true
watch_config: true
debug: false
komorebi:
     start_command: "komorebic start --whkd"
     stop_command: "komorebic stop --whkd"
     reload_command: "komorebic reload-configuration"
bars:
     status-bar:
          enabled: true
          screens: [ '*' ]
          class_name: "yasb-bar"
          alignment:
               position: "top"
          blur_effect:
               enabled: false
               acrylic: true
               dark_mode: true
               round_corners: true
               border_color: None
          window_flags:
               always_on_top: true
               windows_app_bar: true
               hide_on_fullscreen: true
          dimensions:
               width: "100%"
               height: 40
          padding:
               top: 3
               left: 3
               bottom: 0
               right: 3
          animation:
               enabled: true
               duration: 400
          widgets:
               left: [ "komorebi_workspaces" ]
               center: [ "clock" ]
               right: [ "komorebi_stack", "volume", "bluetooth", "power_menu" ]
widgets:

     power_menu:
          type: "yasb.power_menu.PowerMenuWidget"
          options:
               label: "‚èª"
               uptime: true
               blur: false
               blur_background: true
               animation_duration: 200 # Milliseconds
               button_row: 5 # Number of buttons in a row, min 1 max 5
               buttons:
                    lock: [ "Ó©µ", "Lock" ]
                    sleep: [ "‚èæ", "Sleep" ]
                    signout: [ "Û∞çÉ", "Sign out" ]
                    shutdown: [ "ÔÄë", "Shut Down" ]
                    restart: [ "Ó´í", "Restart" ]
                    hibernate: [ "Ôäé", "Hibernate" ]
                    cancel: [ "Û∞ú∫", "Cancel" ]
               label_shadow:
                    enabled: false
                    color: "black"
                    radius: 3
                    offset: [ 1, 1 ]

     volume:
          type: "yasb.volume.VolumeWidget"
          options:
               label: "üîà{level}"

     bluetooth:
          type: "yasb.bluetooth.BluetoothWidget"
          options:
               label: "<span>·öº·õí : {icon}</span> {device_count}"
               label_alt: "{device_name}"
               label_no_device: "No devices connected"
               label_device_separator: ", "
               max_length: 10
               max_length_ellipsis: "..."
               icons:
                    bluetooth_on: "ON"
                    bluetooth_off: "OFF"
                    bluetooth_connected: ""
               callbacks:
                    on_left: "exec cmd.exe /c start ms-settings:bluetooth"

     komorebi_stack:
          type: "komorebi.stack.StackWidget"
          options:
               label_window: "{process}"
               label_window_active: "{title}"
               label_no_window: "¬Ø\\_( Õ°¬∞ Õú ñ Õ°¬∞)_/¬Ø"
               label_zero_index: false
               label_offline: "(‡≤• _ ‡≤•)  {{{(>_<)}}}  ÔºàÔºû‰∫∫ÔºúÔºõÔºâ            Komorebi Offline            „Å§Ôπè‚äÇ .¬∑¬¥¬Ø`(>‚ñÇ<)¬¥¬Ø`¬∑.  o(T„ÉòTo)"
               show_icons: "always"
               icon_size: 10
               max_length: 12
               max_length_active: 60
               max_length_ellipsis: "..."
               hide_if_offline: false
               show_only_stack: false
               animation: true
               enable_scroll_switching: false

     clock:
          type: "yasb.clock.ClockWidget"
          options:
               label: "{%a. ‚ü° %d/%m/%y ‚ü° %H:%M:%S}"
               class_name: "clock"

     komorebi_workspaces:
          type: "komorebi.workspaces.WorkspaceWidget"
          options:
               label_workspace_btn: "    "
               label_workspace_active_btn: ""
               label_workspace_populated_btn: "    "
               label_default_name: ""
               label_zero_index: false
               hide_empty_workspaces: false
               hide_if_offline: true
               animation: true
               app_icons:
                    enabled_populated: true
                    enabled_active: true
                    size: 15
                    max_icons: 0
                    hide_label: true
                    hide_duplicates: true
                    hide_floating: true
